name: Main Workflow

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            extra-trusted-
          set_as_trusted_user: true
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          extraPullNames: |
            nix-community
            devenv
      - run: nix profile add nixpkgs#devenv
      - run: devenv shell -- nixpkgs-lint .
      - run: devenv shell -- treefmt .
